/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\HumanCharacterDummy_M.glb -o src\app\components\HumanCharacterDummy_M.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/HumanCharacterDummy_M.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="B-root">
            <primitive object={nodes['B-hips']} />
            <group name="B-spineProxy" position={[0, 1.063, 0.023]} rotation={[0.006, 0, 0]} />
          </group>
          <skinnedMesh name="HumanM_BodyMesh" geometry={nodes.HumanM_BodyMesh.geometry} material={materials.DefaultMaterial} skeleton={nodes.HumanM_BodyMesh.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/HumanCharacterDummy_M.glb')
